<a href="https://colab.research.google.com/github/JongHyun070105/MachineLearning2025/blob/main/3710%EB%B0%95%EC%A2%85%ED%98%84_numpy_practice_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 기본 연산 문제


### 1. `arr1 = np.array([[1, 2, 3], [4, 5, 6]])` 과 `arr2 = np.array([[6, 5, 4], [3, 2, 1]])`가 주어졌을 때, 두 배열의 덧셈 결과를 출력하세요.


In [2]:
import numpy as np

arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[6, 5, 4], [3, 2, 1]])
arr1 + arr2

array([[7, 7, 7],
       [7, 7, 7]])

### 2. 위와 동일한 `arr1`과 `arr2`를 사용하여 뺄셈 결과를 출력하세요.


In [3]:
arr1 - arr2

array([[-5, -3, -1],
       [ 1,  3,  5]])

### 3. 두 배열의 원소별 곱셈을 수행하세요.


In [4]:
arr1 * arr2

array([[ 6, 10, 12],
       [12, 10,  6]])

### 4. 두 배열의 원소별 나눗셈을 수행하세요.


In [5]:
arr1 / arr2

array([[0.16666667, 0.4       , 0.75      ],
       [1.33333333, 2.5       , 6.        ]])

### 5. `arr1`의 각 원소를 제곱한 결과를 출력하세요.


In [6]:
np.power(arr1, 2)

array([[ 1,  4,  9],
       [16, 25, 36]])

### 6. `arr1`의 각 원소에 대해 제곱근(`sqrt`) 연산을 수행하세요.


In [7]:
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

### 7. `arr1`의 각 원소를 **2로 나눈 몫(`//`)과 나머지(`%`)**를 각각 출력하세요.


In [10]:
print(arr1 // 2)
print(arr1 % 2)

[[0 1 1]
 [2 2 3]]
[[1 0 1]
 [0 1 0]]


## 브로드캐스팅과 다양한 연산 문제


### 8. `arr = np.array([[1, 2, 3], [4, 5, 6]])` 에 10을 더한 결과를 출력하세요. (브로드캐스팅 활용)


In [11]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
np.cast[int](arr) + 10

array([[11, 12, 13],
       [14, 15, 16]])

### 9. `arr`의 각 원소에 대해 3을 곱한 결과를 출력하세요.


In [12]:
np.cast[int](arr) * 3

array([[ 3,  6,  9],
       [12, 15, 18]])

### 10. 1차원 배열 `np.array([1, 2, 3])` 과 2차원 배열 `np.array([[10], [20], [30]])`를 더했을 때 결과를 예측하고 실제 출력하여 확인하세요.


In [13]:
np.array([1,2,3]) + np.array([[10],[20],[30]])

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

### 11. `arr = np.array([[1, 2, 3], [4, 5, 6]])`에서 최대값, 최소값을 각각 구하세요.


In [16]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(np.max(arr))
print(np.max(arr))

6
6


### 12. `arr`의 행별 합(`sum`)과 열별 합(`sum`)을 각각 구하세요.


In [20]:
print(np.sum(arr, axis = 0))
print(np.sum(arr,axis= 1))

[5 7 9]
[ 6 15]


### 13. `arr`의 평균(`mean`)과 표준편차(`std`)를 계산하세요.


In [19]:
np.mean(arr)
np.std(arr)

1.707825127659933

### 14. `arr`를 `arr.T`를 사용하여 전치(`transpose`)하고 결과를 확인하세요.


In [21]:
arr.T

array([[1, 4],
       [2, 5],
       [3, 6]])

## 조건 연산 및 응용 문제


### 15. `arr = np.array([[1, 2, 3], [4, 5, 6]])`에서 모든 원소가 4 이상인 요소만 출력하세요.


In [29]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

result = arr[(arr >= 4)]
print(result)

[4 5 6]


### 16. `arr`의 각 원소가 3보다 크면 1, 작거나 같으면 0이 되도록 변환한 배열을 만드세요.

> 인용구 추가




In [33]:
result = np.where(arr > 3, 1, 0)
result

array([[0, 0, 0],
       [1, 1, 1]])

### 17. `arr`의 각 원소에 대해 로그(`log`) 연산을 수행하세요. (0이 포함되어 있다면 에러 발생 가능)


In [35]:
np.log(arr)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947]])

### 18. 난수를 사용하여 `(3, 3)` 크기의 배열을 만들고, 각 원소를 반올림(`round`)하세요.


In [40]:
arr = np.random.rand(3, 3)
arr = np.round(arr)
arr

array([[0., 0., 1.],
       [0., 0., 0.],
       [0., 1., 0.]])

### 19. 1부터 20까지의 정수를 가진 `5×4` 배열을 생성하고, 짝수만 출력하세요.


In [50]:
arr = np.arange(1, 21).reshape(5, 4)
print(arr[arr % 2 == 0])


[ 2  4  6  8 10 12 14 16 18 20]


### 20. 난수를 사용하여 `(4, 4)` 크기의 배열을 생성하고, `0.5` 이상인 값만 남기고 나머지는 `0`으로 변경하세요.


In [ ]:
arr = np.random.rand(4, 4)
arr = np.where(arr >= 0.5, arr, 0)
arr
