<a href="https://colab.research.google.com/github/JongHyun070105/MachineLearning2025/blob/main/3710%EB%B0%95%EC%A2%85%ED%98%84_numpy_practice_05.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 배열의 형태 변경 (Reshape)


### 1. 1부터 20까지의 정수를 가지는 1차원 배열을 생성하고, 이를 (4,5) 크기의 2차원 배열로 변환하세요.


In [2]:
import numpy as np
np.arange(1, 21).reshape(4, 5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

### 2. (3,4,2) 형태의 3차원 배열을 생성하고, 이를 (6,4) 형태의 2차원 배열로 변환하세요.


In [12]:
arr = np.arange(24).reshape(2,3,4)

arr.reshape(6,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

### 3. (2,6) 형태의 배열을 1차원 배열로 변환하세요.


In [13]:
arr = np.arange(12).reshape(2,6)

arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

### 4. `np.reshape()`을 사용하여 원래 배열의 데이터를 유지하면서 (2,3,2) 형태의 3차원 배열을 생성하세요.


In [14]:
np.arange(12).reshape(2,3,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

### 5. -1을 활용하여 (4,-1) 형태로 변환하면 자동으로 몇 개의 열이 생성되는지 확인하세요.


In [17]:
np.arange(4).reshape(4,-1)

array([[0],
       [1],
       [2],
       [3]])

## 배열 차원 변경 (Expand_dims, Squeeze)


### 6. 1차원 배열 `[1, 2, 3, 4, 5]`을 2차원 배열로 변경하세요. (행 방향과 열 방향 각각 적용)


In [22]:
arr = np.arange(1,6)

print(arr.reshape(1,-1))
print(arr.reshape(-1,1))

[[1 2 3 4 5]]
[[1]
 [2]
 [3]
 [4]
 [5]]


### 7. 3차원 배열을 `np.squeeze()`를 사용하여 2차원 배열로 변환하세요.


In [24]:
arr = np.arange(24).reshape(2,3,4)

print(np.squeeze(arr))

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


### 8. `np.expand_dims()`를 사용하여 1차원 배열을 3차원 배열로 변환하세요.


In [26]:
arr = np.arange(10)
np.expand_dims(arr,axis = 0)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

### 9. 2차원 배열의 특정 차원을 확장하여 3차원 배열로 변환하세요.


In [28]:
arr = np.arange(10).reshape(2,5)

arr.reshape(2,1,5)

array([[[0, 1, 2, 3, 4]],

       [[5, 6, 7, 8, 9]]])

## 차원 및 축 (Axis)


### 10. 3차원 배열 `(2,3,4)`를 생성한 후, `axis=0`, `axis=1`, `axis=2`를 기준으로 합계를 계산하세요.


In [29]:
arr = np.arange(24).reshape(2,3,4)

print(np.sum(arr, axis = 0))
print(np.sum(arr, axis = 1))
print(np.sum(arr, axis = 2))

[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]
[[12 15 18 21]
 [48 51 54 57]]
[[ 6 22 38]
 [54 70 86]]


### 11. 4x5 배열을 생성하고, 행(`axis=1`)과 열(`axis=0`) 기준으로 최댓값을 찾으세요.


In [30]:
arr = np.arange(20).reshape(4,5)

print(np.max(arr, axis = 1))
print(np.max(arr, axis = 0))

[ 4  9 14 19]
[15 16 17 18 19]


### 12. 5x5 배열에서 각 행의 평균과 각 열의 평균을 구하세요.


In [31]:
arr = np.arange(25).reshape(5,5)

print(np.mean(arr, axis = 1))
print(np.mean(arr, axis = 0))

[ 2.  7. 12. 17.]


## 고급 배열 변형


### 13. 3차원 배열을 생성한 후 `transpose()` 함수를 사용하여 차원을 변경하세요.


In [37]:
arr = np.arange(27).reshape(3,3,3)

arr.transpose()

array([[[ 0,  9, 18],
        [ 3, 12, 21],
        [ 6, 15, 24]],

       [[ 1, 10, 19],
        [ 4, 13, 22],
        [ 7, 16, 25]],

       [[ 2, 11, 20],
        [ 5, 14, 23],
        [ 8, 17, 26]]])

### 14. `np.ravel()`을 사용하여 다차원 배열을 1차원 배열로 변환하세요.


In [39]:
np.ravel(arr)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

### 15. 배열을 `reshape()`과 `flatten()`을 각각 사용하여 1차원으로 변환한 뒤, 두 결과가 동일한지 비교하세요.


In [46]:
arr = np.arange(27).reshape(3,3,3)

print(arr.reshape(-1),'\n')
print(arr.flatten())

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26] 

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]
