<a href="https://colab.research.google.com/github/JongHyun070105/MachineLearning2025/blob/main/3710%EB%B0%95%EC%A2%85%ED%98%84_numpy_practice_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 1차원 배열 인덱싱


### 1. `arr = np.arange(10)`을 생성한 후, 인덱스를 이용하여 3번째 원소를 출력하세요.


In [9]:
import numpy as np
arr = np.arange(10)
print(arr[2])

2


### 2. 위 배열에서 마지막 원소를 출력하세요.


In [5]:
print(arr[-1])

9


### 3. `arr`에서 2번째부터 5번째까지의 원소를 출력하세요.


In [8]:
print(arr[1:4])

[1 2 3]


### 4. `arr`에서 짝수 인덱스에 해당하는 값들만 출력하세요.


In [11]:
print(arr[0::2])

[0 2 4 6 8]


### 5. `arr`에서 역순으로 배열을 출력하세요.


In [16]:
print(arr[::-1])

[9 8 7 6 5 4 3 2 1 0]


## 2차원 배열 인덱싱


### 6. `arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])`을 생성한 후, (1,1) 위치의 값을 출력하세요.


In [17]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr[1,1])

5


### 7. 위 배열에서 첫 번째 행을 출력하세요.


In [19]:
print(arr[0:1])

[[1 2 3]]


### 8. 위 배열에서 두 번째 열을 출력하세요.


In [31]:
print(arr[:,1])

[2 5 8]


### 9. 위 배열에서 대각선 요소(1,5,9)를 출력하세요.


In [32]:
print(np.diag(arr))

[1 5 9]


### 10. 위 배열에서 마지막 행의 모든 값을 출력하세요.


In [34]:
print(arr[2:])

[[7 8 9]]


## 3차원 배열 인덱싱


### 11. `arr = np.arange(27).reshape(3,3,3)`을 생성하고, (2,1,0) 위치의 값을 출력하세요.


In [36]:
arr = np.arange(27).reshape(3,3,3)
print(arr[2,1,0])

21


### 12. 위 배열에서 첫 번째 행렬을 출력하세요.


In [41]:
print(arr[:1])

[[[0 1 2]
  [3 4 5]
  [6 7 8]]]


### 13. 위 배열에서 두 번째 열의 모든 행렬 요소를 출력하세요.


In [43]:
print(arr[1:2])

[[[ 9 10 11]
  [12 13 14]
  [15 16 17]]]


### 14. 위 배열에서 마지막 차원의 모든 원소를 출력하세요.


In [44]:
print(arr[2:])

[[[18 19 20]
  [21 22 23]
  [24 25 26]]]


### 15. 위 배열에서 특정 조건을 만족하는 값(예: 값이 10보다 큰 요소)을 출력하세요.

> 인용구 추가




In [53]:
result = arr[arr > 10]
print(result)

[11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26]


## 부울 인덱싱 및 조건부 인덱싱


### 16. `arr = np.array([3, 7, 1, 9, 2, 6])`에서 값이 5보다 큰 요소들만 출력하세요.


In [54]:
arr = np.array([3,7,1,9,2,6])

result = arr[arr > 5]
print(result)

[7 9 6]


### 17. `arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])`에서 값이 50 이상인 요소를 출력하세요.


In [64]:
arr = np.array([[10,20,30],[40,50,60],[70,80,90]])

result = arr[arr > 50]
print(result)

[60 70 80 90]


### 18. 위 배열에서 값이 30 또는 80인 요소를 출력하세요.


In [72]:
result = arr[(arr == 30) | (arr == 80)]
result

array([30, 80])

## 고급 인덱싱


### 19. `arr = np.array([10, 20, 30, 40, 50])`에서 인덱스 배열 `idx = np.array([0, 2, 4])`을 사용하여 해당 위치의 값을 출력하세요.


In [83]:
arr = np.array([10,20,30,40,50])

idx = np.array([0,2,4])

print(arr[idx])

[10 30 50]


### 20. `arr = np.array([[1, 2], [3, 4], [5, 6]])`에서 인덱스 배열을 사용하여 (0,1), (2,0) 위치의 값을 출력하세요.


In [92]:
arr = np.array([[1,2],[3,4],[5,6]])

print(arr[0,1],arr[2,0])

2 5
