<a href="https://colab.research.google.com/github/JongHyun070105/MachineLearning2025/blob/main/3710%EB%B0%95%EC%A2%85%ED%98%84_numpy_practice_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## N차원 배열 생성하기


### 1. numpy를 np라는 이름으로 불러오고, 1차원 배열 [10, 20, 30, 40, 50]을 생성하여 출력하세요.


In [ ]:
import numpy as np

arr = np.array([10,20,30,40,50])
print(arr)

[10 20 30 40 50]


### 2. 2차원 배열 [[1, 2, 3], [4, 5, 6]]을 생성하고, 해당 배열의 shape을 출력하세요.


In [ ]:
arr1 = np.array([[1,2,3],[4,5,6]])
print(arr1.shape)

(2, 3)


### 3. 3차원 배열을 생성하고 ndim 속성을 사용하여 배열의 차원을 출력하세요.


In [ ]:
arr2 = np.array([[[1,2,3],[4,5,6]]])
print(arr2.ndim)

3


### 4. dtype 속성을 이용하여 np.array([1.2, 2.3, 3.4])의 데이터 타입을 출력하세요.


In [ ]:
print(np.array([1.2,2.3,3.4]).dtype)

float64


## N차원 배열의 데이터 타입


### 5. [1, 2, 3]을 리스트로 생성했을 때와 넘파이 배열로 생성했을 때의 type() 값을 비교하여 출력하세요.


In [ ]:
li = [1,2,3]
arr = np.array([1,2,3])

print(li,type(li))
print(arr,type(arr))

[1, 2, 3] <class 'list'>
[1 2 3] <class 'numpy.ndarray'>


### 6. np.array([1, 2, 3], dtype=np.float32)를 생성하고 해당 배열의 데이터 타입을 출력하세요.


In [ ]:
print(np.array([1,2,3],dtype=np.float32).dtype)

float32


### 7. np.array([1.5, 2.5, 3.5], dtype=int)를 생성하고 출력을 했을 때의 결과를 예측하고 실행해보세요.


In [ ]:
# 2, 3, 4 -> 예측 실패 (자리 수를 반올림 하는 것이 아닌 버림)

print(np.array([1.5, 2.5, 3.5], dtype = int))

[1 2 3]


### 8. astype()을 사용하여 정수 배열을 실수 배열로 변환하고 출력하세요.


In [ ]:
print(np.array([1,2,3]).astype(float))

[1. 2. 3.]


## 정해진 형식의 N차원 배열 생성하기


### 9. 3x3 크기의 0으로 채워진 배열을 생성하세요.


In [ ]:
print(np.zeros((3,3)))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### 10. 4x2 크기의 1로 채워진 배열을 생성하세요.


In [ ]:
print(np.ones((4,2)))

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


### 11. 5x5 크기의 모든 원소가 7인 배열을 생성하세요.


In [ ]:
print(np.full((5,5),7))

[[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]]


### 12. np.eye(4)을 사용하여 4x4 단위 행렬을 생성하세요.


In [ ]:
print(np.eye(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### 13. np.linspace(0, 100, 5)를 사용하여 0에서 100까지 5개의 원소를 가지는 배열을 생성하세요.


In [ ]:
print(np.linspace(0,100,5))

[  0.  25.  50.  75. 100.]


## 난수로 이루어진 N차원 배열 생성하기


### 14. np.random.rand(3,3)을 사용하여 3x3 크기의 난수 배열을 생성하세요.


In [ ]:
np.random.rand(3,3)

array([[0.8582036 , 0.16233993, 0.60915703],
       [0.49086211, 0.09964579, 0.94967774],
       [0.98175147, 0.08517673, 0.29253764]])

### 15. np.random.randn(4,4)을 사용하여 평균이 0이고, 표준편차가 1인 정규 분포를 따르는 4x4 크기의 배열을 생성하세요.


In [ ]:
np.random.randn(4,4)

array([[-0.19489203, -1.56527135,  0.04507047,  0.28496486],
       [ 1.99462232, -0.47981562, -0.24136313,  0.49767514],
       [-0.73194894,  0.93658098,  1.80017209, -0.01741024],
       [ 0.16972206, -1.06027489,  0.40748883,  0.46819551]])

### 16. np.random.randint(10, size=(3,3))을 사용하여 0에서 9 사이의 정수 난수로 이루어진 3x3 배열을 생성하세요.


In [ ]:
np.random.randint(10,size=(3,3))

array([[1, 9, 8],
       [0, 0, 7],
       [7, 6, 9]])

## 시드값을 통한 난수 생성 제어


### 17. np.random.seed(42)를 설정한 후, np.random.rand(3,3)을 실행하고 다시 실행했을 때 같은 결과가 나오는지 확인하세요.


In [ ]:
np.random.seed(42)
np.random.rand(3,3)

array([[0.37454012, 0.95071431, 0.73199394],
       [0.59865848, 0.15601864, 0.15599452],
       [0.05808361, 0.86617615, 0.60111501]])

### 18. np.random.seed(100)을 설정한 후, np.random.randint(1, 100, 10)을 실행하여 결과를 확인하세요.


In [ ]:
np.random.seed(100)
np.random.randint(1,100,10)

## 추가 문제


### 19. np.arange(1, 21).reshape(4,5)를 사용하여 4x5 배열을 생성하고 출력하세요.


In [ ]:
arr = np.arange(1,21).reshape(4,5)
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


### 20. 위에서 생성한 배열에서 2번째 행을 가져와 출력하세요.


In [ ]:
print(arr[1:2])

[[ 6  7  8  9 10]]
