<a href="https://colab.research.google.com/github/JongHyun070105/MachineLearning2025/blob/main/3710%EB%B0%95%EC%A2%85%ED%98%84_Numpy_practice_06.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## NumPy 배열 원소 추가, 삭제 및 병합 관련 실습 문제


### 1. 배열 원소 추가 및 삭제


#### 1. 1부터 10까지의 숫자로 이루어진 1차원 배열을 생성하고, 인덱스 3번째 위치에 50을 추가하세요.


In [2]:
import numpy as np
arr = np.arange(1,10)
arr = np.insert(arr, 2, 50)
arr

array([ 1,  2, 50,  3,  4,  5,  6,  7,  8,  9])

#### 2. (3,4) 크기의 2차원 배열을 생성한 후, 행(`axis=0`) 방향으로 새로운 행 `[10,20,30,40]`을 추가하세요.


In [6]:
arr = np.arange(12).reshape(3,4)
arr = np.insert(arr, 0, [10,20,30,40], axis=0)
arr

array([[10, 20, 30, 40],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

#### 3. 위의 2차원 배열에서 열(`axis=1`) 방향으로 새로운 열 `[100,200,300]`을 추가하세요.


In [8]:
arr = np.insert(arr, 0, [100,200,300,400], axis=1)
arr

array([[100,  10,  20,  30,  40],
       [200,   0,   1,   2,   3],
       [300,   4,   5,   6,   7],
       [400,   8,   9,  10,  11]])

#### 4. 1차원 배열에서 인덱스 5에 있는 원소를 삭제하세요.


In [9]:
arr = np.arange(10)

np.delete(arr, 5)

array([0, 1, 2, 3, 4, 6, 7, 8, 9])

#### 5. 2차원 배열에서 행(`axis=0`) 기준으로 2번째 행을 삭제하세요.


In [12]:
arr = np.arange(20).reshape(4,5)

arr = np.delete(arr, 2 , axis = 0)
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [15 16 17 18 19]]


### 2. 배열 병합 및 분할


#### 6. 두 개의 (3,3) 크기의 2차원 배열을 생성하고, 이를 `axis=0` 방향으로 병합하세요.


In [15]:
arr1 = np.arange(9).reshape(3,3)

arr2 = np.arange(9).reshape(3,3)

np.concatenate((arr1, arr2), axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 7. 위의 배열을 `axis=1` 방향으로 병합하세요.


In [16]:
arr1 = np.arange(9).reshape(3,3)

arr2 = np.arange(9).reshape(3,3)

np.concatenate((arr1, arr2), axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

#### 8. 1차원 배열 `[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]`을 세 개의 배열로 균등하게 분할하세요.


In [17]:
arr = np.arange(1, 10)

np.split(arr,3)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]

#### 9. (4,4) 크기의 배열을 두 개의 `(2,4)` 배열로 분할하세요.


In [22]:
arr1 = np.arange(16).reshape(4,4)
arr2 = np.arange(16).reshape(4,4)

print(np.split(arr1,[2,4]),'\n')
print(np.split(arr2,[2,4]))

[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]]), array([], shape=(0, 4), dtype=int64)] 

[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]]), array([], shape=(0, 4), dtype=int64)]


#### 10. (6,6) 크기의 배열을 수직(`vsplit`) 및 수평(`hsplit`)으로 각각 세 부분으로 나누세요.


In [25]:
arr = np.arange(36).reshape(6,6)

print(np.vsplit(arr,3),'\n')
print(np.hsplit(arr,3))


[array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]]), array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]]), array([[24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])] 

[array([[ 0,  1],
       [ 6,  7],
       [12, 13],
       [18, 19],
       [24, 25],
       [30, 31]]), array([[ 2,  3],
       [ 8,  9],
       [14, 15],
       [20, 21],
       [26, 27],
       [32, 33]]), array([[ 4,  5],
       [10, 11],
       [16, 17],
       [22, 23],
       [28, 29],
       [34, 35]])]
