<a href="https://colab.research.google.com/github/JongHyun070105/MachineLearning2025/blob/main/3710%EB%B0%95%EC%A2%85%ED%98%84_numpy_practice_04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 1차원 배열의 정렬 문제


### 1. 0부터 50까지의 난수를 가지는 크기 10의 1차원 배열을 생성하고, 오름차순으로 정렬하세요.


In [20]:
import numpy as np

arr = np.random.randint(0, 51, size=10)

sorted_arr = np.sort(arr)
sorted_arr

array([ 1,  3, 13, 16, 18, 29, 34, 34, 34, 42])

### 2. 위에서 생성한 배열을 내림차순으로 정렬하세요.


In [28]:
np.sort(arr,axis = 0)[::-1]

array([42, 34, 34, 34, 29, 18, 16, 13,  3,  1])

### 3. `np.sort()`와 `np.argsort()`를 사용하여 배열의 정렬된 값과 해당 값의 원래 인덱스를 출력하세요.


In [31]:
print(np.sort(arr))
print(np.argsort(arr))

[ 1  3 13 16 18 29 34 34 34 42]
[5 4 9 3 2 0 1 7 8 6]


## 2차원 배열의 정렬 문제


### 4. `(3,4)` 크기의 2차원 배열을 난수로 생성한 후, 행 기준(`axis=1`)으로 정렬하세요.


In [32]:
arr = np.random.randn(3,4)
np.sort(arr, axis = 1)

array([[-2.13672516e+00, -1.20073118e+00,  7.61834622e-01,
         1.34510768e+00],
       [-1.84878131e+00, -5.71539772e-01, -3.22638657e-01,
         1.01710900e+00],
       [-1.08181257e+00, -8.73035842e-01, -7.42004943e-01,
        -6.47825543e-04]])

### 5. 위의 2차원 배열을 열 기준(`axis=0`)으로 정렬하세요.


In [33]:
np.sort(arr, axis = 0)

array([[-1.20073118e+00, -2.13672516e+00, -7.42004943e-01,
        -6.47825543e-04],
       [-1.08181257e+00, -1.84878131e+00, -5.71539772e-01,
         1.01710900e+00],
       [-3.22638657e-01, -8.73035842e-01,  7.61834622e-01,
         1.34510768e+00]])

### 6. 2차원 배열을 1차원 배열로 변환한 후, 정렬하세요.


In [41]:
arr = np.ravel(arr)
np.sort(arr)

array([-2.13672516e+00, -1.84878131e+00, -1.20073118e+00, -1.08181257e+00,
       -8.73035842e-01, -7.42004943e-01, -5.71539772e-01, -3.22638657e-01,
       -6.47825543e-04,  7.61834622e-01,  1.01710900e+00,  1.34510768e+00])

## 정렬된 배열에서 값 찾기 문제


### 7. 크기가 `(4,5)`인 2차원 난수 배열을 생성하고, `np.argmax()`와 `np.argmin()`을 사용하여 각 행(row)별 최댓값과 최솟값의 인덱스를 찾으세요.


In [60]:
arr = np.random.randint(0,10,size = (4,5))
print(np.argmax(arr))
print(np.argmin(arr))

5
9


### 8. `np.where()`를 사용하여 2차원 배열에서 특정 값(예: 7 이상인 값)의 위치를 찾으세요.


In [62]:
indices = np.where(arr >= 7)  # 7 이상인 값의 인덱스 찾기

print(indices)

(array([0, 0, 1, 1, 2, 2, 3]), array([1, 4, 0, 3, 1, 4, 3]))


## 사용자 정의 정렬 적용 문제


### 9. 주어진 1차원 배열 `[3, 1, 9, 7, 5]`을 정렬하되, 홀수를 먼저 정렬하고 짝수를 나중에 정렬하는 사용자 정의 정렬을 구현하세요.


In [64]:
arr = [3, 1, 9, 7, 5]

odd_nums = sorted([num for num in arr if num % 2 != 0])
even_nums = sorted([num for num in arr if num % 2 == 0])

new_arr = odd_nums + even_nums
new_arr


[1, 3, 5, 7, 9]

### 10. 문자열 배열 `['apple', 'banana', 'cherry', 'blueberry']`를 문자열 길이 기준으로 정렬하세요.


In [67]:
arr = ['apple', 'banana', 'cherry', 'blueberry']

arr.sort(key =len)
arr

['apple', 'banana', 'cherry', 'blueberry']