<a href="https://colab.research.google.com/github/JongHyun070105/MachineLearning2025/blob/main/Numpy_%EA%B8%B0%EC%B4%88_2025_03_11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 배열에 원소 추가 및 삭제

In [2]:
import numpy as np

In [5]:
# 리스트

li = list(range(1,9))
print(li)
li.insert(2,50) # insert(위치, 삽입할 값)
print(li)

# 1차원 배열
arr = np.arange(1,9)
print(arr)
arr = np.insert(arr, 2, 50)
print(arr)

[1, 2, 3, 4, 5, 6, 7, 8]
[1, 2, 50, 3, 4, 5, 6, 7, 8]
[1 2 3 4 5 6 7 8]
[ 1  2 50  3  4  5  6  7  8]


In [10]:
arr = np.arange(1,13).reshape(3,4)
print(arr,'\n\n')

arr = np.insert(arr, 2, 50, axis=0)
print(arr,'\n\n')

arr = np.insert(arr, 2, 50, axis=1)
print(arr,'\n\n')

arr = np.insert(arr, 2, 50) # axis 를 지정하지 않으면 1차원으로 변형하여 추가
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 


[[ 1  2  3  4]
 [ 5  6  7  8]
 [50 50 50 50]
 [ 9 10 11 12]] 


[[ 1  2 50  3  4]
 [ 5  6 50  7  8]
 [50 50 50 50 50]
 [ 9 10 50 11 12]] 


[ 1  2 50 50  3  4  5  6 50  7  8 50 50 50 50 50  9 10 50 11 12]


In [12]:
# delete

arr = np.arange(1,13).reshape(3,4)
print(arr,'\n\n')

arr = np.delete(arr, 2, axis=0)
print(arr,'\n\n')

arr = np.delete(arr, 2, axis=1)
print(arr,'\n\n')

arr = np.delete(arr, 2) # axis 를 지정하지 않으면 1차원으로 변형하여 추가
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 


[[1 2 3 4]
 [5 6 7 8]] 


[[1 2 4]
 [5 6 8]] 


[1 2 5 6 8]


# 배열간의 병합

In [19]:
# append
arr = np.arange(1,13).reshape(3,4)
arr1 = np.arange(13,25).reshape(3,4)

print(arr,'\n\n',arr1, '\n\n')

arr2 = np.append(arr,arr1, axis = 0)
print(arr2,'\n\n')

arr3 = np.append(arr,arr1, axis = 1)
print(arr3,'\n\n')

arr4 = np.append(arr, arr1) # axis를 생략하면 1차원으로 변환하여 병합
print(arr4)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

 [[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]] 


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]] 


[[ 1  2  3  4 13 14 15 16]
 [ 5  6  7  8 17 18 19 20]
 [ 9 10 11 12 21 22 23 24]] 


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


# vstack() / hsctack()

## numpy.vstack(튜플)

In [25]:
arr1 = np.arange(1,7).reshape(2,3)
arr2 = np.arange(7,13).reshape(2,3)

print(arr1,'\n\n',arr2,'\n\n')

arr3 = np.vstack((arr1,arr2)) # vstack => aixs = 0 을 기준으로 병합하는 함수
print(arr3,'\n\n')

arr4 = np.hstack((arr1,arr2)) # hstack => aixs = 1 을 기준으로 병합하는 함수
print(arr4)


[[1 2 3]
 [4 5 6]] 

 [[ 7  8  9]
 [10 11 12]] 


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] 


[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


# concatenate()

In [26]:
arrt = np.concatenate((arr1,arr2), axis = 0)
print(arrt,'\n\n')

arrh = np.concatenate((arr1,arr2), axis = 1)
print(arrh)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] 


[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


# split()

In [42]:
arr = np.arange(1,13).reshape(3,4)
print(arr,'\n\n')

arr1 = np.split(arr, 3, axis = 0)
print(arr1,'\n',type(arr1),'\n\n') # numpy 배열구조를 가지고 있다

arr2 = np.vsplit(arr, 3)
print(arr2,'\n','\n\n')

arr3 = np.hsplit(arr, 2)
print(arr3,'\n')

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 


[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([[ 9, 10, 11, 12]])] 
 <class 'list'> 


[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([[ 9, 10, 11, 12]])] 
 


[array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12]])] 



In [46]:
arr1 = np.full([3,4,5],3)
print(arr1)

[[[3 3 3 3 3]
  [3 3 3 3 3]
  [3 3 3 3 3]
  [3 3 3 3 3]]

 [[3 3 3 3 3]
  [3 3 3 3 3]
  [3 3 3 3 3]
  [3 3 3 3 3]]

 [[3 3 3 3 3]
  [3 3 3 3 3]
  [3 3 3 3 3]
  [3 3 3 3 3]]]


다음 조건에 맞는 배열을 생성하시오
- 족너1) 정수 -50 ~ 50 범위의 정수형 난수로 이루어진 배열의 형태
- 조건2) 행을 기준으로 오름차순 정렬하여 출력
- 조건3) 전체 배열을 1차원 배열로 변경하여 오름차순으로 정렬

In [75]:
arr2 = np.random.randint(-50,50,(4,5))
print(np.sort(arr2,axis = 0),'\n')
print(np.sort(arr2, axis = None))

[[-31 -47 -28 -50 -28]
 [-19 -47 -15 -49 -16]
 [  1 -41 -15 -34  27]
 [ 33  36  38   2  46]] 



In [113]:
py_list = [
           np.full(3,8),
           np.array([33,-15,26]),
           np.linspace(17,26,3)]

result = []

for i in py_list :
  result.append(np.mean(i))
  result.append(np.std(i))
  result.append(np.median(i))

  print(result)


[8.0, 0.0, 8.0]
[8.0, 0.0, 8.0, 14.666666666666666, 21.171259344267224, 26.0]
[8.0, 0.0, 8.0, 14.666666666666666, 21.171259344267224, 26.0, 21.5, 3.6742346141747673, 21.5]
