<a href="https://colab.research.google.com/github/JongHyun070105/MachineLearning2025/blob/main/Numpy_%EA%B8%B0%EC%B4%88_2025_03_07.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# dot product

In [2]:
# 2차열
import numpy as np

arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[-5,6],[7,8]])

print(np.dot(arr1,arr2))

[[ 9 22]
 [13 50]]


In [19]:
# 절대값 구하기
print(np.abs(arr2))

[[5 6]
 [7 8]]


In [6]:
arr1 = np.array([[1,592,-6,12945],[3,3484,-586,4]])

# 올림함수
print(np.ceil(arr1))

# 내림함수
print(np.floor(arr1))

# 반올림함수
print(np.round(arr1))

# 버림함수
print(np.trunc(arr1))

[[ 1.0000e+00  5.9200e+02 -6.0000e+00  1.2945e+04]
 [ 3.0000e+00  3.4840e+03 -5.8600e+02  4.0000e+00]]
[[ 1.0000e+00  5.9200e+02 -6.0000e+00  1.2945e+04]
 [ 3.0000e+00  3.4840e+03 -5.8600e+02  4.0000e+00]]
[[    1   592    -6 12945]
 [    3  3484  -586     4]]
[[ 1.0000e+00  5.9200e+02 -6.0000e+00  1.2945e+04]
 [ 3.0000e+00  3.4840e+03 -5.8600e+02  4.0000e+00]]


In [18]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

# max() 최대값 구하기
print(np.max(arr))
print(arr.max(axis=0))
print(arr.max(axis=1))

print("")

# min() 최소값 구하기
print(np.min(arr))
print(arr.min(axis=0))
print(arr.min(axis=1))

print("")

# sum() 합계 구하기
print(np.sum(arr))
print(arr.sum(axis=0))
print(arr.sum(axis=1))

print("")

# mean() 평균 구하기
print(np.mean(arr))
print(arr.mean(axis=0))
print(arr.mean(axis=1))

print("")

# std() 표준편차 구하기
print(np.std(arr))
print(arr.std(axis=0))
print(arr.std(axis=1))

print("")

# cusmsum() 누적 합계 구하기
print(np.cumsum(arr))
print(arr.cumsum(axis=0))
print(arr.cumsum(axis=1))

print("")

# median() 중앙값 구하기
print(np.median(arr))
print(np.median(arr,axis=0))
print(np.median(arr,axis=1))

9
[7 8 9]
[3 6 9]

1
[1 2 3]
[1 4 7]

45
[12 15 18]
[ 6 15 24]

5.0
[4. 5. 6.]
[2. 5. 8.]

2.581988897471611
[2.44948974 2.44948974 2.44948974]
[0.81649658 0.81649658 0.81649658]

[ 1  3  6 10 15 21 28 36 45]
[[ 1  2  3]
 [ 5  7  9]
 [12 15 18]]
[[ 1  3  6]
 [ 4  9 15]
 [ 7 15 24]]

5.0
[4. 5. 6.]
[2. 5. 8.]


# 배열의 삼각함수 / 비교연

In [22]:
arr = np.array([[1,2,3],[4,5,6]])

arr2 = np.array([[7,8,9],[-1,-2,-3]])

# 비교연산 (대응되는 원소끼리 비교)
print(arr == arr2)

print(np.array_equal(arr,arr2))

[[False False False]
 [False False False]]
False


In [23]:
# 삼각함수

# sin()
print(np.sin(arr))

print("")

# cos()
print(np.cos(arr))

print("")

# tan()
print(np.tan(arr))

[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]]

[[ 0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029]]

[[ 1.55740772 -2.18503986 -0.14254654]
 [ 1.15782128 -3.38051501 -0.29100619]]


# 브로드캐스팅

In [27]:
# 버전 1
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2 = np.array([1,2,3])

print(arr1 + arr2)

[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]


In [28]:
# 버전 2
arr1 = np.array([1,1,1])
arr2 = np.array([[0],[1],[2]])

print(arr1 + arr2)

[[1 1 1]
 [2 2 2]
 [3 3 3]]


In [29]:
import time

In [32]:
arr = np.arange(999999999)

In [34]:
# for - 큰 수치를 계산할수록 오래걸림

sum = 0
before = time.time()
for i in arr :
  sum += i
after = time.time()

print(sum, after - before, "초")

KeyboardInterrupt: 

In [35]:
# 벡터 연산 - for문에 비해 엄청나게 빠름

before = time.time()
sum = np.sum(arr)
after = time.time()

print(sum, after - before, "초")

499999998500000001 0.9148764610290527 초


In [36]:
arr1 = np.arange(99999)
arr2 = np.arange(99999)

In [37]:
# for
# zip - 데이터의 개수가 동일한 자료에 대해서 사용할 수 있음

sum = 0
before = time.time()
for i,j in zip(arr1, arr2) :
  sum += i*j
after = time.time()

print(sum,after - before)

333318333549999 0.03386259078979492


In [38]:
# 벡터연산

before = time.time()
sum = np.dot(arr1,arr2)
after = time.time()

print(sum, after - before, "초")

333318333549999 0.0013358592987060547 초


# N차원 배열의 정렬

## 1차원 배열의 정렬

In [39]:
arr = np.random.randint(10,size = 10)
print(arr)

[6 9 9 2 9 8 8 2 1 9]


In [43]:
print(np.sort(arr))
print(np.sort(arr)[::-1])

[1 2 2 6 8 8 9 9 9 9]
[9 9 9 9 8 8 6 2 2 1]


In [44]:
print(arr)

[1 2 2 6 8 8 9 9 9 9]


In [47]:
arr_s = np.sort(arr)
print(arr_s)

arr.sort()
print(arr)

[1 2 2 6 8 8 9 9 9 9]
[1 2 2 6 8 8 9 9 9 9]


## 2차원 배열의 정렬

In [53]:
arr = np.random.randint(20,size=(3,4))
print(arr)
print('')
print(np.sort(arr))

[[16  7 13 12]
 [13  5  2  3]
 [19 10 15 18]]

[[ 7 12 13 16]
 [ 2  3  5 13]
 [10 15 18 19]]


In [57]:
print(np.sort(arr,axis=0))
print('')
print(np.sort(arr,axis=1))
print('')
print(np.sort(arr,axis=None)) # 1차원 배열로 변경해서 오름차순 정렬

[[13  5  2  3]
 [16  7 13 12]
 [19 10 15 18]]

[[ 7 12 13 16]
 [ 2  3  5 13]
 [10 15 18 19]]

[ 2  3  5  7 10 12 13 13 15 16 18 19]


In [59]:
# argsort() 정렬된 원소의 원래배열에서의 인덱스를 반환

print(arr,'\n\n')
print(np.sort(arr, axis = 0), '\n\n')
print(np.argsort(arr, axis = 0))

[[16  7 13 12]
 [13  5  2  3]
 [19 10 15 18]] 


[[13  5  2  3]
 [16  7 13 12]
 [19 10 15 18]] 


[[1 1 1 1]
 [0 0 0 0]
 [2 2 2 2]]


## n차원 배열의 형태 변경

### 배열의 형태 변경 1
- reshape()

In [60]:
arr = np.arange(12)
print(arr,arr.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11] 1


In [61]:
arr = arr.reshape((3,4))
print(arr,arr.ndim)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 2


In [63]:
arr = arr.reshape((2,3,2))
print(arr,arr.ndim)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]] 3


In [64]:
arr = np.arange(36).reshape(3,4,3)
print(arr,arr.ndim)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]] 3


In [69]:
arr = arr.reshape((2,2,3,3))
print(arr,arr.ndim)

[[[[ 0  1  2]
   [ 3  4  5]
   [ 6  7  8]]

  [[ 9 10 11]
   [12 13 14]
   [15 16 17]]]


 [[[18 19 20]
   [21 22 23]
   [24 25 26]]

  [[27 28 29]
   [30 31 32]
   [33 34 35]]]] 4


### 배열의 형태 변경 2
- resize
- revel

In [78]:
arr = np.arange(12)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [79]:
arr.resize(3,4) # resize 함수는 배열의 shape을 변경해주는데, 원본 데이터 형태가 변경된다
print(arr,arr.ndim)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 2


In [80]:
print(arr.ravel()) # ravel 함수는 1차원 배열로 변경해주는 함수
print(arr)
arr = arr.ravel()
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [85]:
# 1차원 배열
arr = np.arange(1,13)
print(arr)

# 2차원 배열로 reshape
arr = arr.reshape(-1,6)
print(arr)

# 3차원 배열로 reshape
arr = arr.reshape((2,-1,3))
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


### 배열의 형태 변경 3
- expand_dims
- squeeze

In [86]:
arr = np.arange(13)
print(arr, arr.shape)

arrs = np.expand_dims(arr, axis = 0)
print(arrs, arrs.shape)

arrs = np.expand_dims(arr, axis = 1)
print(arrs, arrs.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12] (13,)
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12]] (1, 13)
[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]] (13, 1)
